### ISSUE TITLE
Custom nested schemas not serialized in list view

### ISSUE THREAD

**Issue by mcaldas** [ForestAdmin/forest-express-mongoose#79] opened 2017-08-30 12:29 UTC
On list view i see something like `<client@model:forest-users-someschema::ember5328:owner(XXXXXXXX)>` for custom types.
I would expect having the serialized content there.

Also in filters i cannot filter by a sub field of the custom schema, is this a separate issue?

**Comment by mcaldas** [comment] 2017-08-30 12:29
@arnaudbesnier

**Comment by arnaudbesnier** [comment] 2017-09-05 14:42
Yes we have this issue in mind. I'll let you know if we can add this in the next sprint.

**Comment by lucasscariot** [comment] 2017-09-18 13:10
Hi @mcaldas !
Can you send me an example of the your model to help me reproduce the bug?

**Comment by mcaldas** [comment] 2017-09-18 13:39
I shared an example model in #76 , is that enough?

**Comment by mcaldas** [comment] 2017-09-19 18:09
@lucasscariot

**Comment by arnaudbesnier** [comment] 2017-09-27 07:29
@mcaldas, it is not clear enough, I cannot reproduce with your example.
Using the latest liana version (1.3.0), I don't have such issue.

The bad serialisation you have seems to be related to a `users`/`someschema` schema, but you example in the issue https://github.com/ForestAdmin/forest-express-mongoose/issues/76 does not reflect that.

Can you send us the minimal code to reproduce the case:
- using the latest liana version,
- with the full model declaration (give us the whole file),
- with some screenshots of the bug in the UI.

Thanks for the help.

**Comment by mcaldas** [comment] 2017-09-27 22:17
@arnaudbesnier let me verify this on latest liana and get back to you

**Comment by mcaldas** [comment] 2017-10-02 18:42
@arnaudbesnier i tried on v1.4.4 and still happens the same for 2 different type of types.
See attached screenshot of what i  see.
Can you give me your email or something so i can send the full schema there?

<img width="677" alt="screen shot 2017-10-02 at 21 05 58" src="https://user-images.githubusercontent.com/3955907/31093346-1c2395d0-a7ba-11e7-90a5-50a0d9b5cd55.png">

**Comment by arnaudbesnier** [comment] 2017-10-04 13:12
hi @mcaldas, the `location` column issue is related to the `mongoose.Schema.Types.Point` support (cf. your other issue https://github.com/ForestAdmin/forest-express-mongoose/issues/78).

About the `status_line` display issue, I am sorry but I can't reproduce this (considering the model you sent by email).
And you should not have a column displayed for such a complex field. I think you felt in a weird state.
I'll clean your UI for you.

**Comment by arnaudbesnier** [comment] 2017-10-04 13:19
@mcaldas I cleaned your projects, it should be fixed.
Feel free to reopen if it is not properly fixed.

🌲🌲🌲

(let's discuss the remaining issue you have on the other ticket)

**Closed** 2017-10-04 13:19 UTC
Labels: bug
