### ISSUE TITLE
Can't use site at all

### ISSUE THREAD

**Issue by fourpixels** [ForestAdmin/forest-express-mongoose#6] opened 2016-06-17 12:00 UTC
Hi there,
I just wanted to try to register and use Forest Admin. I used the signup form, entered my info, and actually entered the admin panel (didn't receive any e-mail for that). I tried to use the standard 'users' collection, and then I just got redirected to my url:

https://app.forestadmin.com/1096/login

**BUT** it's stating Unlock Test Admin • Development -> your forest password.

And no matter what I do - I cannot unlock it (even though I enter my password). I even reset it (got e-mail and updated my pass) - still no luck.

**THERE IS NO CONTACT INFO** on the website! How can you think people will spend money on something they can't even reach! What a shame...

Not to mention it somehow tries to connect to my provided url, which as an **example** was **localhost**. Had to open a tunnel and it still didn't work out..

Is there any real way to actually try your service?

**Comment by VinzGhyz** [comment] 2016-06-17 13:38
Hello,

That is odd, it seems on our end that everything is correctly set up. I've sent you an email so that we can take care of your issue on a quick call, will be easier!

The behaviour of connecting to your localhost is in fact perfectly normal: requests are initiated by the client which mean, on your local machine, localhost is actually reachable. This is perfectly fine and nothing to be alarmed by, if your local server is up and running it should work.

We are aware of the lack of contact info and are working towards adding those, thanks for bringing that up. Please also note we are at the moment contacting everyone that starts the process to counter that shortcoming.

Happy to help further, you now have my email address as well.
Vincent

**Comment by fourpixels** [comment] 2016-06-27 12:05
We've chatted over Skype and you couldn't find why I didn't have token in my headers, but had to go.. So what's up now, fixed? :)

**Comment by VinzGhyz** [comment] 2016-06-27 12:26
Oops, that's my bad you're right. We are still looking into this issue, there seems to be something off regarding the authentication. Will let you know as soon as the situation changes!

**Comment by wesreid** [comment] 2016-08-11 03:47
Same issue here
![forest unlock issue](https://8172ba483412c27553e9de0a24343c7e5dc5d73b.googledrive.com/host/0B_v2MoSrEF-CWDBGMUVtNjBCWk0/forest-issue.png "Forest Admin Unlocking Issue")

Any ideas?

**Comment by wesreid** [comment] 2016-08-11 04:03
Ok - it wasn't clear to me that I had to use the generator for the secret keys. How do I delete the above account "211" so that I can use that email address?

**Comment by fourpixels** [comment] 2016-08-11 06:09
Well how you've used that? :)
It's been like two months now and there is not any single response from these guys. I wonder how they think I'm going to use their product...

**Comment by VinzGhyz** [comment] 2016-08-11 10:17
@wesreid Happy to see you've got it sorted out! I can delete the DMX Admin Portal project if you want, or you can head over to app.forestadmin.com/new-project to create a new one with the same account. Let me know if you need anything else.

@fourpixels Admittedly, we've lost a bit of momentum regarding mongoose support as we've got customers that had feature requests in our other stacks. We try to prioritize those when there's a choice to be made, we're also looking at hiring additional developers to maintain all the connectors. I'll have another look at your issue now, and let you know what I can find!

**Comment by wesreid** [comment] 2016-08-11 13:50
@VinzGhyz - thanks for the response. If you can delete the DMX Admin Portal project, that would be greatly appreciated.

A few more important questions:
Are you saying that Mongoose is not a priority and is not supported?
Should I not create a new dashboard using Mongoose?
Is Express still being supported?
Is Sequelize kept current and is it being supported?

Basically, you tell me which is the best options for tech stack for forest.

Thanks

**Comment by VinzGhyz** [comment] 2016-08-11 16:03
@wesreid I looked into your issue a bit more, and it appears that you had duplicated accounts which was the root cause here. Took care of that and kept your latest project created. 

As for your questions: 
Wrong choice of words -that's on me-, Mongoose is definitely still actively supported it just so happens that we've had more people using the other connectors lately. Same goes for Express in general and Sequelize, which are all under active development.

We've created Forest so that it's universal and does not rely on a particular stack, so I would advise you to choose whichever one makes the most sense considering your business' needs.

**Comment by arnaudbesnier** [comment] 2016-11-18 22:17
Hi guys,

I close the issue, the problem should not happen anymore.
@fourpixels, If you still can't log in to your project on Forest, please reopen the issue. I would be happy to help!

**Closed by arnaudbesnier** 2016-11-18 22:17 UTC

**Comment by halleyrv** [comment] 2019-03-04 20:31
Hi I have the some problem what is the solution?

**Comment by idahogurl** [comment] 2019-10-01 18:42
I have the same problem @halleyrv

**Comment by halleyrv** [comment] 2019-10-01 20:46
Hi @idahogurl  I could not solution this , but i work with other gem in rails for backend this is treslte is flexible admin with rails this is the link

https://github.com/TrestleAdmin/trestle

**Comment by arnaudbesnier** [comment] 2019-10-02 06:23
Hi @halleyrv @idahogurl ,
You can join our community to have "live" support (https://community.forestadmin.com/).

As the initial issue is pretty old, I think that the odds that the causes are different are high.
So feel free to re-open a new issue with a full description of your integration problems.

@halleyrv, this is the repository of the Node.js/Express/Mongoose Forest liana. Can you detail why a Rails gem is a good alternative? Is your backend based on Node.js or Rails?

Thanks!
